### ISSUE TITLE
Any workaround?

### ISSUE THREAD

**Issue by ldiqual** [prendio2/StackViewWow#1]
@prendio2 I'm experiencing the same issue on a complex layout. Sometimes setting `isHidden = false` multiple times in a row will fix the issue, but it's very unpredictable. Have you found a workaround?

**Comment by bcse** [comment]
A possible workaround: call setHidden before animation block and call layoutIfNeeded in animation block.

**Comment by prendio2** [comment]
My workaround is to just check if the view is already hidden or not before trying to hide it:

```objective-c
- (void)setView:(UIView *)view asHidden:(BOOL)hidden
{
  // Only hide views that aren't already hidden to avoid stack view bug
  if (view.hidden != hidden) {
    view.hidden = hidden;
  }
}
```
